#!/usr/bin/env bash

mkdir -p "$HOME/.local/src"
git clone -b v0.12.4 https://github.com/neovim/neovim.git "$HOME/.local/src/neovim"
cd "$HOME/.local/src/neovim" || exit
make CMAKE_BUILD_TYPE=Release
sudo make install


